import type { Metadata } from "next";
import {
  Mochiy_Pop_One,
  Plus_Jakarta_Sans,
} from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/contexts/LanguageContext";
import BackToTop from "@/components/BackToTop";
import WhatsAppFloat from "@/components/WhatsAppFloat";



const mochiyPopOne = Mochiy_Pop_One({
  variable: "--font-mochiy-pop-one",
  subsets: ["latin"],
  weight: "400",
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mochiyPopOne.variable} ${plusJakartaSans.variable} antialiased`}
      >
        <LanguageProvider>
          {children}
          <BackToTop />
          <WhatsAppFloat />
        </LanguageProvider>
      </body>
    </html>
  );
}
